enableTelemetry: false

packageExtensions:
  "@typescript-eslint/utils@8.6.0":
    dependencies:
      typescript: "*"
  "@typescript-eslint/type-utils@8.6.0":
    dependencies:
      eslint: "*"

pnpMode: strict